### ISSUE TITLE
Different drinks can be selected

### ISSUE THREAD

**Issue by ardazeytin** [serhatuzunbayir/VENDINGMACHINE-2_AliSinan_Ataberk_Arda#1]
Missing drinks can be found at the link below.
[Nuka-Cola Types](http://fallout.wikia.com/wiki/Nuka-Cola)

**Comment by alisinancoban** [comment]
If i see one more command-line app, you are fired.

**Comment by ardazeytin** [comment]
Now, user can select different type of Nuka cola. You can fire yourself.
